services:
  api:
    # build the image from the local Dockerfile
    build: .

    # tag the resulting image
    image: nextnonce-backend:latest

    # load runtime secrets / config
    env_file:
      - .env

    # map host → container port (override host port with PORT env-var if you like)
    ports:
      - "${HOST_PORT-3000}:3000"

    # always restart unless you stop it explicitly
    restart: unless-stopped

    # ← limits valid for plain `docker compose up`
    cpus: "4.0"          # allow up to 4 vCPUs
    mem_limit: 8g        # hard RAM ceiling
    mem_reservation: 1g  # soft reservation